version: "3.9"
    
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always    
    environment:
      MYSQL_ROOT_PASSWORD: teamf
      MYSQL_DATABASE: wordpress
      MYSQL_USER: teamf
      MYSQL_PASSWORD: teamfpwd
    networks:
      - net
  nginx:
    image: nginx:alpine
    volumes:
      - nginx:/etc/nginx/conf.d
      - wp_data:/var/www/html
    ports:
      - 8093:80
    links:
      - wordpress
    networks:
      - net
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wp_data:/var/www/html
    ports:
      - "8094:80"
    networks:
      - net
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: teamf
      WORDPRESS_DB_PASSWORD: teamfpwd
      WORDPRESS_DB_NAME: wordpress
volumes:
  db_data: {}
  wp_data: {}
  nginx: {}
networks:
  net: {}
